---
- name: add openITCOCKPIT repository key
  become: yes
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com'
    id: A7D3EAFA

- name: add openITCOCKPIT repository
  become: yes
  apt_repository:
    repo: 'deb https://apt.open-itcockpit.com {{ os }} main'
    filename: openitcockpit
    state: present
    update_cache: yes

- name: ensure that dbconfig-common folder ist present
  become: yes
  file:
    path: /etc/dbconfig-common
    state: directory

- name: set dbconfig-common
  become: yes
  template:
    src: openitcockpit.conf.j2
    dest: /etc/dbconfig-common/config
    owner: root
    group: root
    mode: 0600

- name: set phpnsta config
  become: yes
  template:
    src: phpnsta_config.php.j2
    dest: /etc/dbconfig-common/phpnsta_config.php

- name: install naemon and dependancies
  become: yes
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  with_items:
    - expect
    - openitcockpit
    - openitcockpit-common
    - openitcockpit-naemon
    - openitcockpit-statusengine-naemon
    - openitcockpit-npcd
    - openitcockpit-mysql
    - openitcockpit-monitoring-plugins
  register: setup_packages

- name: set database config
  become: yes
  template:
    src: database.php.j2
    dest: /usr/share/openitcockpit/app/Config/database.php
    owner: www-data
    group: www-data
    mode: 0600`